### ISSUE TITLE
email notifications

### ISSUE THREAD

**Issue by emmaclarkefestinalente** [KeithClarke/FestinaLente#30]
Would it be possible after the user fills in a form to have the Main Form and the Special Needs \ Therapeutic Rider forms going in an email to clodagh@festinalente.ie & accounts@festinalente.ie with a full list of all the filled in fields in the email so that we have a soft copy of all forms? Can you send the Supported Helper form to kirsten@festinalente.ie and accounts@festinalente.ie?

**Comment by KeithClarke** [comment]
Yes can do. Will take a couple of hours of coding.

**Comment by emmaclarkefestinalente** [comment]
Format sent by email is what we are looking for so please go ahead with this
