### ISSUE TITLE
Field Searches

### ISSUE THREAD

**Issue by emmaclarkefestinalente** [KeithClarke/FestinaLente#31]
As you know I am not a developer so if I want to get a list of my fields to see the data in them (prior to deletion) how do I search for this as I used to do searches based off the main contacts view from the live ui?

**Comment by KeithClarke** [comment]
I've added an "x " prefix to the labels of the fields that I'd like you to review and delete. So you can create new views on the Contacts home page that list those side by side wit the replacements that I listed in the email. Not pleasant work but a good double check step on the work I did to transfer that data into the new fields
