### ISSUE TITLE
Which Page Layout do i edit?

### ISSUE THREAD

**Issue by emmaclarkefestinalente** [KeithClarke/FestinaLente#32]
If I want to make changes to fields and page layouts what layout do I edit as this is not clear to me know as there are now 5 listed in the Contact Page Layout list?

**Comment by KeithClarke** [comment]
If you click the "Page Layout Assignment" button you will see that the one being used now is the "Local Contact Client Layout" and it is that one you should edit. (The "Contact Client Layout" is what gets pushed in from my development org.)

**Comment by emmaclarkefestinalente** [comment]
Thank you
